### PR TITLE
Fix parameter setting, add print density and print break time options

### PR DESCRIPTION
**Pull request by rudcode**
1. Fix parameter setting: Manual said it's ESC 7 in ascii or 27 55 in decimal
2. Add print density and print break time options: Page 48 of the manual
3. Add more options for interval

### CODE REVIEW

**Review by edrosten — APPROVED** [review]
OK, but how did it ever work???

**Comment by rudcode** [comment]
I think most printer actually accept 2 value  7 and '7', but my printer print garbage value if using 7 instead of '7'.

**Comment by edrosten** [comment]
Interesting!  I don't currently have a printer: it's now in the project it ended up in. I'm going to get another one, because they're really fun!

Also, what does the print density do? How does it differ from heating time, any idea? Would also be good to know what model you have.

**Comment by rudcode** [comment]
Yes, they're really fun!

I think it's the dpi setting, in my printer the default value is 50%, when I set it to 100% the resolution is higher. I think my printer is some clone of adafruit thermal printer, or maybe from the same manufacturer but different branding, from outside it looks the same, but the firmware is different. When printing test page it says the system version is m701 and firmware version 2.40xxsomething.

**Pull request merged**
